# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\x1f\n\x0cStockRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"D\n\rStockResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x10\n\x08in_stock\x18\x03 \x01(\x08\x32\x93\x01\n\tInventory\x12\x41\n\nCheckStock\x12\x17.inventory.StockRequest\x1a\x18.inventory.StockResponse\"\x00\x12\x43\n\nWatchStock\x12\x17.inventory.StockRequest\x1a\x18.inventory.StockResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=30
  _globals['_STOCKREQUEST']._serialized_end=61
  _globals['_STOCKRESPONSE']._serialized_start=63
  _globals['_STOCKRESPONSE']._serialized_end=131
  _globals['_INVENTORY']._serialized_start=134
  _globals['_INVENTORY']._serialized_end=281
# @@protoc_insertion_point(module_scope)
